pipeline {
    agent { node { label 'AGENT-1' } }

    parameters {
        string(name: 'Version', defaultValue: '1.0.1', description: 'Which version to Deploy')
    }

    stages {
        stage('Deploy') {
            steps {
                echo "Deploying..."
            }
        }
    }
    stages {
        stage('Init') {
            steps {
                sh """
                    cd terraform
                    terraform init -reconfigure
                """
            }
        }
        stage('Plan') {
            steps {
                sh """
                    cd terraform
                    terraform plan
                """
            }
        }
    }
    post {
        always {
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
}
 